---
version: '3.7'
services:
  bbugyi200.sync_or_swim:
    build:
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/sync_or_swim:delegated
    working_dir: /sync_or_swim
    environment:
      - BETTER_EXCEPTIONS
      - CC_REPO_URL
